# 本地环境
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/freedom?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
        username: root

crawl-storage-folder: /Users/luoyanjie